-- ═══════════════════════════════════════════════════
-- SEED DATA — Enoch's Dedication Guest List
-- 109 guests across tables 1–15
-- Overflow tables 16, 17, 18 included empty for walk-ins
-- ═══════════════════════════════════════════════════

-- Assign design variants to tables (cycling through 8 variants)
insert into event_tables (table_number, design_variant_id) values
  (1, 1),
  (2, 2),
  (3, 3),
  (4, 4),
  (5, 5),
  (6, 6),
  (7, 7),
  (8, 8),
  (9, 1),
  (10, 2),
  (11, 3),
  (12, 4),
  (13, 5),
  (14, 6),
  (15, 7),
  (16, 8),
  (17, 1),
  (18, 2);

-- Guests
insert into guests (slug, full_name, table_number) values
  ('p-victor-francis-qmjb0', 'P. Victor Francis', 1),
  ('p-faith-francis-nnq66', 'P. Faith Francis', 1),
  ('p-bade-olotu-lhfps', 'P. Bade Olotu', 1),
  ('mrs-bola-olotu-cqb5e', 'Mrs Bola Olotu', 1),
  ('dcn-nnanna-okorie-7cn4h', 'Dcn Nnanna Okorie', 1),
  ('kachi-okorie-wxik4', 'Kachi Okorie', 1),
  ('dami-moks-ui126', 'Dami Moks', 1),
  ('mr-olusegun-akintola-5z2np', 'Mr Olusegun Akintola', 1),
  ('pst-adeyemi-oyewole-1w9wq', 'Pst. Adeyemi Oyewole', 2),
  ('mrs-joy-oyewole-ubz2u', 'Mrs Joy Oyewole', 2),
  ('mr-adekunle-adejumo-0a2d6', 'Mr Adekunle Adejumo', 2),
  ('mr-israel-oribamise-zwop8', 'Mr. Israel Oribamise', 2),
  ('mrs-grace-oribamise-qe5fx', 'Mrs Grace Oribamise', 2),
  ('mr-and-mrs-lanii-bs2i2', 'Mr and Mrs Lanii', 2),
  ('mrs-olanipekun-olajumoke-a7kgr', 'Mrs Olanipekun Olajumoke', 2),
  ('dr-and-dr-mrs-mojeed-ola-gda2c', 'Dr. and Dr Mrs Mojeed Oladokun', 3),
  ('sijuwade-bamimore-isx6o', 'Sijuwade Bamimore', 3),
  ('morenike-george-1tnhu', 'Morenike George', 3),
  ('ada-ry0av', 'Ada', 3),
  ('mr-and-mrs-mordi-3k9gq', 'Mr and Mrs Mordi', 3),
  ('mr-and-mrs-temitope-thom-qbqwi', 'Mr and Mrs Temitope Thomas and Family', 3),
  ('bayo-ojo-e28s0', 'Bayo Ojo', 4),
  ('kai-ojo-gwc1m', 'Kai Ojo', 4),
  ('mr-and-mrs-yemi-adewusi-zr6vf', 'Mr and Mrs Yemi Adewusi', 4),
  ('beloved-adeyemi-ild36', 'Beloved Adeyemi', 4),
  ('marvellous-1g3n4', 'Marvellous', 4),
  ('temi-moses-kwe0t', 'Temi Moses', 4),
  ('ignitious-ocansey-mj6cs', 'Ignitious Ocansey', 5),
  ('nelly-ocansey-fm1vr', 'Nelly Ocansey', 5),
  ('bro-gbolahan-say4t', 'Bro Gbolahan', 5),
  ('sis-olamide-z3t7k', 'Sis Olamide', 5),
  ('mr-stephen-moses-vlek8', 'Mr Stephen Moses', 5),
  ('mrs-kehinde-moses-1rnw9', 'Mrs Kehinde Moses', 5),
  ('mr-and-mrs-ogunsakin-2j8j4', 'Mr and Mrs Ogunsakin', 5),
  ('benedicta-onoharigho-xh8fj', 'Benedicta Onoharigho', 6),
  ('fred-onoharigho-1h2ur', 'Fred Onoharigho', 6),
  ('konye-nwabunike-3u5lv', 'Konye Nwabunike', 6),
  ('alex-nwabunike-oqclt', 'Alex Nwabunike', 6),
  ('beauty-obadan-0rxui', 'Beauty Obadan', 6),
  ('izegaegbe-obadan-86nto', 'Izegaegbe Obadan', 6),
  ('vera-obadan-gtugn', 'Vera Obadan', 6),
  ('florence-smith-29v3p', 'Florence Smith', 6),
  ('ese-duku-omlgq', 'Ese Duku', 7),
  ('uruemu-duku-itmw8', 'Uruemu Duku', 7),
  ('tawa-f2xap', 'Tawa', 7),
  ('ugochi-anuonye-p9hg3', 'Ugochi Anuonye', 7),
  ('eniola-e75tt', 'Eniola', 7),
  ('adewale-adeyemi-0df4r', 'Adewale Adeyemi', 7),
  ('damilola-adeyemi-2qutp', 'Damilola Adeyemi', 7),
  ('segun-lotana-dfhaj', 'Segun Lotana', 7),
  ('toluwase-aragbuwa-dwzm6', 'Toluwase Aragbuwa', 8),
  ('olawale-aragbuwa-ak3qj', 'Olawale Aragbuwa', 8),
  ('seyi-obiyemi-3dc0c', 'Seyi Obiyemi', 8),
  ('jumoke-obiyemi-xvhu3', 'Jumoke Obiyemi', 8),
  ('opeyemi-fakeye-gdq33', 'Opeyemi Fakeye', 8),
  ('marho-omasan-hl5bk', 'Marho Omasan', 8),
  ('moninuola-omasan-qq7rr', 'Moninuola Omasan', 8),
  ('mr-and-mrs-ushedo-ohlel', 'Mr and Mrs Ushedo', 9),
  ('patience-odeh-mjr0p', 'Patience Odeh', 9),
  ('ben-odeh-vj6w8', 'Ben Odeh', 9),
  ('abosede-olu-frederick-9kd3s', 'Abosede Olu-Frederick', 9),
  ('adeshina-precious-0oha2', 'Adeshina Precious', 9),
  ('mr-and-mrs-uzezi-eddy-pjgo0', 'Mr and Mrs Uzezi-Eddy', 9),
  ('oluwatosin-obiyemi-11dll', 'Oluwatosin Obiyemi', 10),
  ('obilekan-obiyemi-pbdy3', 'Obilekan Obiyemi', 10),
  ('jadesola-ogundele-55fny', 'Jadesola Ogundele', 10),
  ('olumuyiwa-bamidele-7idhl', 'Olumuyiwa Bamidele', 10),
  ('justina-bamidele-b3fvx', 'Justina Bamidele', 10),
  ('ibrahim-ogundele-nj5h5', 'Ibrahim Ogundele', 10),
  ('josephine-sunday-szzcj', 'Josephine Sunday', 10),
  ('nnamdi-solomon-ibewuike-w6d7i', 'Nnamdi Solomon Ibewuike', 10),
  ('timilehin-sabo-hhc7d', 'Timilehin Sabo', 11),
  ('lucky-sabo-zmuyf', 'Lucky Sabo', 11),
  ('enitan-alo-m0pua', 'Enitan Alo', 11),
  ('anu-alo-pu4ab', 'Anu Alo', 11),
  ('akinsete-olakunle-56ya5', 'Akinsete Olakunle', 11),
  ('simo-larissa-garq2', 'Simo Larissa', 11),
  ('taiwo-yaroglah-15nc6', 'Taiwo Yaroglah', 11),
  ('omoniyi-yaroglah-tn4k1', 'Omoniyi Yaroglah', 11),
  ('tobiloba-lawal-hipob', 'Tobiloba Lawal', 12),
  ('oluwole-lawal-fzq9v', 'Oluwole Lawal', 12),
  ('mr-and-mrs-olayinka-ibra-3b5kj', 'Mr and Mrs Olayinka Ibraheem', 12),
  ('philip-kelson-gztwp', 'Philip Kelson', 12),
  ('nicola-cabrelli-vl2mi', 'Nicola Cabrelli', 12),
  ('joanne-jack-gc52j', 'Joanne Jack', 12),
  ('lynne-coyle-6lku9', 'Lynne Coyle', 12),
  ('olufemi-frank-adu-ej0dk', 'Olufemi Frank Adu', 13),
  ('mrs-damilola-adu-q30mg', 'Mrs Damilola Adu', 13),
  ('mr-adeyemi-oyedepo-cbaeu', 'Mr Adeyemi Oyedepo', 13),
  ('felicia-oyedepo-bd68z', 'Felicia Oyedepo', 13),
  ('wiktoria-zinoro-t5cee', 'Wiktoria Zinoro', 13),
  ('leroy-zinoro-v57h8', 'Leroy Zinoro', 13),
  ('joy-yinusa-t2h82', 'Joy Yinusa', 13),
  ('tolulope-egunjobi-ksymf', 'Tolulope Egunjobi', 13),
  ('damilola-eguntola-j2bzj', 'Damilola Eguntola', 14),
  ('olateju-eguntola-teejay-06xis', 'Olateju Eguntola (Teejay)', 14),
  ('dare-akande-galao', 'Dare Akande', 14),
  ('sammie-1dq3d', 'Sammie', 14),
  ('genny-a9mu5', 'Genny', 14),
  ('sean-0tu6x', 'Sean', 14),
  ('shina-adewoye-ic44v', 'Shina Adewoye', 14),
  ('titilayo-olateju-f24g1', 'Titilayo Olateju', 14),
  ('oladapo-oginni-jqosq', 'Oladapo Oginni', 15),
  ('mojisola-oginni-bsln0', 'Mojisola Oginni', 15),
  ('omolara-adedokun-60npg', 'Omolara Adedokun', 15),
  ('atilade-adedokun-e1v8i', 'Atilade Adedokun', 15),
  ('lanre-oni-p5qa7', 'Lanre Oni', 15),
  ('tolu-lanre-oni-c88fo', 'Tolu Lanre-Oni', 15),
  ('mr-and-mrs-adewole-2llq4', 'Mr and Mrs Adewole', 15);